# Site settings
# Enter your own credentials here
title: "OFET Structure -> Properties"
email: imperssonator@gmail.com
description: >
  This site will tell you all about everything.
baseurl: "/research-pages" # replace ``/research-pages`` with the name of the parents repository
url: "Materials-Informatics-Lab.github.io" # replate ``Materials-Informatics-Lab`` with your Github username
twitter_username: twitterhandle
disqus: tonyfast

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5


gh:
  user: Imperssonator
  repo: MIC-OFET-Processing
  # Branch hosting Github pages
  branch: gh-pages
